import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface AccessRequestData {
  email: string;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { email }: AccessRequestData = await req.json();

    if (!email) {
      return new Response(
        JSON.stringify({ error: "Email is required" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        }
      );
    }

    console.log("Processing access request for:", email);

    const emailResponse = await resend.emails.send({
      from: "johnnybgsu@gmail.com",
      to: ["john@123185.xyz"],
      subject: "NCare Nigeria - New Access Request",
      html: `
        <h2>New Access Request for NCare Nigeria</h2>
        <p>Someone has requested access to the NCare Nigeria hospital management system.</p>
        
        <h3>Request Details:</h3>
        <ul>
          <li><strong>Email:</strong> ${email}</li>
          <li><strong>Date:</strong> ${new Date().toLocaleDateString()}</li>
          <li><strong>Time:</strong> ${new Date().toLocaleTimeString()}</li>
        </ul>
        
        <p>Please review this request and contact the person if you wish to grant them access.</p>
        
        <hr>
        <p><em>This email was automatically generated by the NCare Nigeria system.</em></p>
      `,
    });

    console.log("Access request email sent successfully:", emailResponse);

    return new Response(
      JSON.stringify({ 
        success: true, 
        message: "Access request submitted successfully" 
      }),
      {
        status: 200,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );

  } catch (error: any) {
    console.error("Error in send-access-request function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);