-- Create laboratory user account
INSERT INTO auth.users (
  id,
  instance_id,
  email,
  encrypted_password,
  email_confirmed_at,
  created_at,
  updated_at,
  confirmation_token,
  role,
  aud,
  email_change_confirm_status,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  confirmed_at,
  email_change,
  email_change_token_new,
  email_change_token_current,
  email_change_sent_at,
  recovery_token,
  recovery_sent_at,
  email_change_token_current_deadline,
  email_change_token_new_deadline
) VALUES (
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'laboratory@demo.com',
  crypt('password123', gen_salt('bf')),
  now(),
  now(),
  now(),
  '',
  'authenticated',
  'authenticated',
  0,
  now(),
  '{"provider": "email", "providers": ["email"]}',
  '{"role": "laboratory"}',
  false,
  null,
  null,
  '',
  '',
  null,
  now(),
  '',
  '',
  '',
  null,
  '',
  null,
  null,
  null
);

-- Create profile for laboratory user
INSERT INTO public.profiles (
  user_id,
  username,
  role,
  hospital_id
) VALUES (
  (SELECT id FROM auth.users WHERE email = 'laboratory@demo.com'),
  'Laboratory Staff',
  'laboratory',
  (SELECT id FROM hospitals LIMIT 1)
);