/**
 * Supabase Client Configuration
 * 
 * This file creates and configures the Supabase client for the NCare Nigeria
 * Hospital Management System. Supabase provides our backend infrastructure
 * including database, authentication, real-time subscriptions, and edge functions.
 * 
 * Configuration includes:
 * - PostgreSQL database with Row Level Security (RLS)
 * - User authentication and session management
 * - Real-time subscriptions for live data updates
 * - Automatic token refresh for seamless user experience
 * 
 * IMPORTANT: This file is automatically generated. Do not edit it directly.
 * 
 * @author NCare Nigeria Development Team
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase project configuration
const SUPABASE_URL = "https://fdonpuxzpptjtdqegguu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkb25wdXh6cHB0anRkcWVnZ3V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjQ1NjgsImV4cCI6MjA2NzIwMDU2OH0.-4TLSira8fZ6ufvbMFAfdNp6bkGaxPN2wFEQ7vqKJV8";

/**
 * Main Supabase client instance
 * 
 * Import and use this client throughout the application:
 * import { supabase } from "@/integrations/supabase/client";
 * 
 * Configuration features:
 * - localStorage: Persists sessions across browser sessions
 * - persistSession: Maintains user login state
 * - autoRefreshToken: Automatically refreshes expired tokens
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});