// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdonpuxzpptjtdqegguu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkb25wdXh6cHB0anRkcWVnZ3V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjQ1NjgsImV4cCI6MjA2NzIwMDU2OH0.-4TLSira8fZ6ufvbMFAfdNp6bkGaxPN2wFEQ7vqKJV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});